baseURL: "https://www.zhouzhoukl.com/"
title: Zhou's Home
# paginate: 5
theme: hugo-PaperModX
# NOTE remove this line if you copy exampleSite outof hugo-PaperModX

enableInlineShortcodes: true
hasCJKLanguage: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
timeZone: Asia/Shanghai

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: Zhou's Home
  author:
    - å‘¨æ´²
  images: 
    - images/avatar.jpeg
  favicon: "https://zhouzhoukl.oss-cn-hangzhou.aliyuncs.com/images/avatar.jpeg"
  logo:
    icon: images/avatar.jpeg
  mainSections:
    - blog
  disableAnchoredHeadings: true
  DateFormat: "2006-01-02"
  useCustomAnalytics: true

  defaultTheme: auto
  # disableThemeToggle: true
  DisableLanguageSwitch: true
  ShowShareButtons: true
  ShareButtons:
    - twitter
    - telegram
  ShowReadingTime: true
  ShowWordCount: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  TocOpen: true
  TocSide: "right"
  EnableInstantClick: true
  EnableImageZoom: true
  Email: kele@thewan.cc

  # commentSystems:
  #   disqus:
  #     shortname: reorx
  #   remark42:
  #     url: https://remark42.reorx.com
  #     site: reorx.github.io
  #   telegramWidget:
  #     channel: reorx_share
  #     accentColor: "9077e1"
  #     limit: 20
  # defaultCommentSystems:
  #   remark42: true

  profileMode:
    enabled: false
    title: PaperModX
    imageUrl: "#"
    imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Archives
        url: /archives/
      - name: Tags
        url: /tags/

  homeInfoParams:
    Title: "Winter is coming. </br > Life goes on."
    Content: |
      Hiï¼Œæˆ‘æ˜¯å‘¨æ´²ï¼Œä»¥ä¸‹æ˜¯ä¸€äº›ç®€å•çš„å…³äºï¼š

      - **åˆ›é€ è€…**

        é™¤äº†ç¼–ç¨‹ä¸è¡Œå•¥éƒ½èƒ½ææçš„åŠåŠå­åˆ›ä¸šè€…ï¼Œæ­£åœ¨åˆ›é€ æœ‰è¶£çš„äº§å“Â·Â·Â·

        é™¤äº†ä¸»ä¸šåœ¨åšçš„äº‹å¤–ï¼Œè¿˜åœ¨åšä¸”å‘å±•ä¸€äº›è‡ªç”±èŒä¸šæˆ–æ˜¯å‰¯ä¸šï¼Œæ¢ç´¢å¤šå…ƒçš„å‘å±•å’Œæ”¶å…¥æ„æˆï¼Œæ¶ˆè€—æ—ºç››çš„ç²¾åŠ›å’Œæ—¶é—´ï¼ˆäº‹æœ‰èŠ‚å¥ï¼Œéš¾ä»¥å¡«æ»¡ï¼‰ï¼Œæ›´é‡è¦çš„æ˜¯æ”¯æ’‘åˆ›ä¸šä½è°·æœŸç­‰ä¸ç¡®å®šæ€§é˜¶æ®µã€‚

      - **ç®€ä»‹**

        INTJ | Dc | 5 | å­˜åœ¨ä¸»ä¹‰

        Cç«¯å·¥å…· | æ¸¸æˆ | ç¤¾äº¤ | XRåº”ç”¨

        ä¼‘è¿‡å­¦ï¼Œåˆ›è¿‡ä¸šï¼Œæ‰“è¿‡å·¥ï¼Œè¿˜åœ¨å­¦ä¹ 

      - **å…¶ä»–**

        èµ·åˆæ˜¯å¬[æ¯›ä¸œçš„æ’­å®¢ğŸ”—](https://www.xiaoyuzhoufm.com/episode/61ce46e94f0dd5de5533ceda)ï¼Œå¾ˆæœ‰æ„Ÿè§¦ã€‚</br >
        ä¸€ç›´æ˜¯ä¸€ä¸ªè®°å¿†å¾ˆå·®çš„äººï¼Œå¾ˆå¤šäººäº‹ç‰©éƒ½æ¶ˆå¤±äº†ï¼Œæ‰€ä»¥æƒ³åšä¸€äº›è®°å½•å»å¯¹æŠ—è®°å¿†ã€‚åŒæ—¶ï¼Œé«˜ä¸­æ—¶æœŸå†™äº†ä¸å°‘æ–‡å­—ï¼Œè¿˜æ˜¯å½“æ—¶é«˜è€ƒè¯­æ–‡çš„æ ¡çŠ¶å…ƒhhï¼Œä½†åœ¨é‚£ä¹‹åå¿™å¿™ç¢Œç¢Œä¼¼ä¹ä¸§å¤±äº†å†™ä½œçš„èƒ½åŠ›ã€‚è€Œä¸”ï¼Œâ€œæˆ‘å°±åƒä¸€æ¡ç”Ÿæ´»åœ¨æ°´é‡Œçš„é±¼ï¼Œä»æ¥æ²¡æœ‰åæ€è¿‡æˆ‘ç”Ÿæ´»çš„è¿™ç‰‡æ°´â€ï¼Œè®°å½•èƒ½å¤Ÿæ›´å¥½åœ°åŠ©åŠ›åæ€å’Œæ´å¯Ÿã€‚</br >
        è€Œç›¸è¾ƒäºç¬¬ä¸‰æ–¹å¹³å°ï¼Œæ­å»ºä¸€ä¸ªå±äºè‡ªå·±çš„ç½‘ç«™ä¼¼ä¹æ˜¯æ›´å¥½çš„é€‰æ‹©ã€‚è¿™å¯¹äºé›¶åŸºç¡€çš„è‡ªå·±ä¹Ÿæ˜¯ä¸€ä¸ªä¸é”™çš„å°è¯•ã€‚

        ä¸è‡ªå·±å¯¹è¯ | å¯¹æŠ—è®°å¿† | äº«å—æŒ‘æˆ˜

      æ‚¨ä¹Ÿå¯ä»¥é€šè¿‡ä»¥ä¸‹é“¾æ¥æ‰¾åˆ°æˆ‘ã€‚

  socialIcons:
    - name: twitter-simple
      url: "https://twitter.com/zhouzhoukl?s=09"
    - name: telegram-simple
      url: "https://t.me/zhouzhoukl"
    - name: default
      url: "https://okjk.co/ko1LjX"
    - name: gmail
      url: "kele@thewan.cc"
    - name: rss-simple
      url: "index.xml"

  links:
    - name: Pseudoyu
      url: https://www.pseudoyu.com
      description: åŒºå—é“¾å¼€å‘å·¥ç¨‹å¸ˆï¼Œå–œæ¬¢æ¢ç´¢æ–°æŠ€æœ¯
      favicon: https://www.pseudoyu.com/images/author.webp
    - name: äº¤æ¢å‹é“¾
      url: https://twitter.com/zhouzhoukl?s=09
      description: å¯å‘é‚®ä»¶è‡³ kele@thewan.cc,æˆ–æ·»åŠ  Telegram @zhouzhouklã€‚
        # æˆ‘çš„åšå®¢ä¿¡æ¯
        # åç§°:Zhou's Home;
        # åœ°å€:https://www.zhouzhoukl.com;
        # å¤´åƒ:https://zhouzhoukl.com/images/avatar.jpeg;
        # æè¿°:ä¼‘è¿‡å­¦ï¼Œåˆ›è¿‡ä¸šï¼Œæ‰“è¿‡å·¥ï¼Œè¿˜åœ¨å­¦ä¹ 
      favicon: https://zhouzhoukl.com/images/avatar.jpeg

  # editPost:
  #   URL: "https://github.com/reorx/hugo-PaperModX/tree/exampleSite/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # label:
  #     text: "Home"
  #     icon: icon.png
  #     iconHeight: 35

  # assets:
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

minify:
  disableXML: true
  # minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Blog
          url: /blog/
          weight: 1
        # - name: Newsletter
        #   url: /newsletter/
        #   weight: 1
        # - name: Tags
        #   url: /tags/
        #   weight: 4
        - name: Archive
          url: /archives/
          weight: 5
        - name: Links
          url: /links/
          weight: 5
        - name: Search
          url: /search/
          weight: 10
        # - name: "Wan. Inc"
        #   url: "https://www.thewan.cc"
        #   params:
        #     external: true

  # zh:
  #   languageName: ":cn:"
  #   languageAltTitle: ä¸­æ–‡
  #   weight: 2
  #   title: PaperModX
  #   profileMode:
  #     enabled: true
  #     title: PaperModX
  #     # imageUrl: "#"
  #     # imageTitle: my image
  #     # imageWidth: 120
  #     # imageHeight: 120
  #     subtitle: >
  #       <p>Hugo ä¸»é¢˜</p>
  #       â˜„ï¸ å¿«é€Ÿ | â˜ï¸ æµç•… | ğŸ“– å¯è¯»æ€§ | ğŸ“± å“åº”å¼
  #     buttons:
  #       - name: æ–‡æ¡£
  #         url: docs
  #       - name: æ ‡ç­¾
  #         url: tags
  #   menu:
  #     main:
  #       - name: æ–‡æ¡£
  #         url: docs
  #         weight: 1
  #       # - name: æ ‡ç­¾
  #       #   url: tags/
  #       #   weight: 4
  #       - name: å½’æ¡£
  #         url: archives
  #         weight: 5
  #       # - name: æœç´¢
  #       #   url: search/
  #       #   weight: 10
  #       # - name: "@ä½œè€…"
  #       #   url: "https://reorx.com"
  #       #   params:
  #       #     external: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula
    lineNos: false
    noClasses: false

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
